# Group files (like this one) should be placed in the
# XDG_CONFIG_HOME/metapac/groups directory (usually ~/.config/metapac/groups)
# unless using the --config-dir cli option.
#
# The packages for each backend in group files can come in two formats, short-form
# and long-form:
#
# short-form syntax is simply a string of the name of the package.
#
# long-form syntax is a table which contains several fields which can
# optionally be set to specify install options on a per-package basis.
# The "package" field in the table specifies the name of the package.
#
# For example, the following two packages are equivalent:
# arch = [
# 	"metapac",
# 	{ package = "metapac" }
# ]

arch = [
	"metapac",
	# optional_deps: additional packages to install with this package, short-form syntax only
	{ package = "metapac",  optional_deps = ["git"] }
]
apt = [
	"metapac",
	{ package = "metapac" }
]
brew = [
	"metapac",
	{ package = "metapac" }
]
cargo = [
	"metapac",
	# see cargo docs for info on the options
	{ package = "metapac", git = "https://github.com/ripytide/metapac", all_features = true, no_default_features = false, features = [ "feature1", ] },
]
dnf = [
	"metapac",
	# see dnf docs for more info on these options
	{ package = "metapac", repo = "/etc/yum.repos.d/fedora_extras.repo" },
]
flatpak = [
	"metapac",
	{ package = "metapac" }
]
pipx = [
	"metapac",
	{ package = "metapac" }
]
rustup = [
	"stable",
	# components: extra non-default components to install with this toolchain
	{ package = "stable", components = ["rust-analyzer"] }
]
xbps = [
	"metapac",
	{ package = "metapac" }
]
